### PR TITLE
add missing use statements

### PR DESCRIPTION
**Pull request by kbond**

### CODE REVIEW

**Comment by kbond** [comment]
ping @beberlei

**Comment by gnugat** [comment]
:+1:

**Comment by kbond** [comment]
There are actually more issues with the pagerfanta adapter/renderer: The adapter must be constructed with a `Result` but the renderer creates the adapter with a `Page`.

I'm not sure what is the best way to solve this...

**Comment by kbond** [comment]
One solution might be to have another pagerfanta adapter: `PagePorpaginasAdapter`. This one would be constructed with `Page` and always return the same results for `getSlice`. The renderer could then use this adapter. It's not pretty...

**Comment by beberlei** [comment]
Lets merge this first.

**Pull request merged**
